info:
  name: @project.artifactId@
  version: @project.version@
  origin: @scm.url@
  commit: @buildNumber@
  branch: @scmBranch@
  built: @timestamp@

management:
  endpoints:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true

server:
  port: 9999

mock:
  port: 9099

spring:
  application:
    name: fwmt-job-service
  http.multipart:
    max-file-size: 12800MB
    max-request-size: 12800MB
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
    virtualhost: /

logging:
  level:
    root: WARN
    uk.gov.ons.fwmt: DEBUG
    org.springframework: ERROR
    org.springframework.security: ERROR
    org.springframework.web: ERROR
    org.hibernate: ERROR
    org.apache.commons.dbcp2: ERROR

  file: target/SpringErrors/spring.log
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] [%X{CID}] [%X{FILENAME}] %logger{1}::%M - %msg%n"
    file:    "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] [%X{CID}] [%X{FILENAME}] %logger{1}::%M - %msg%n"

security.user:
  name: "user"
  password: "password"

totalmobile:
  username: "user"
  password: "pass"
  url: ""
  default_world: "Default"
  modworld: "MOD WORLD"
  message-queue-path: "/Services/TM/v20/Messaging/MessageQueueWs.asmx"
  message-queue-wsdl-path: "src/main/resources/wsdl/Messaging_MessageQueueWs.wsdl"
  message-queue-namespace: "http://schemas.consiliumtechnologies.com/wsdl/mobile/2007/07/messaging/"
  message-queue-package: "com.consiliumtechnologies.schemas.services.mobile._2009._03.messaging"
  outgoing-ws-namespace: "http://schemas.consiliumtechnologies.com/services/mobile/2009/03/messaging"
  web:
    login-url: "/WebAdmin/Login"
    save-user-url: "/WebAdmin/Administration/Users/SaveUser"

rabbitmq:
  initialinterval: 5000
  multiplier: 3.0
  maxInterval: 45000

fwmt:
  workTypes:
    ccs:
      duration: 5
    ce:
      duration: 5
    hh:
      duration: 5
    ohs:
      duration: 5
